interface TermsOfServiceProps {
  companyName: string;
  websiteName: string;
  lastUpdated: string;
  contactEmail: string;
  contactPageUrl: string;
}

const defaultTermsProps: TermsOfServiceProps = {
  companyName: "Mars the Limit",
  websiteName: "Bible Study Buddy",
  lastUpdated: "October 27, 2025",
  contactEmail: "marsthelimit890@gmail.com",
  contactPageUrl: "/#contact",
};

/**
 * Terms of Service Component
 */
const TermsOfService: React.FC<TermsOfServiceProps> = ({
  companyName,
  websiteName,
  lastUpdated,
  contactEmail,
  contactPageUrl,
}) => {
  const subheadingStyle: React.CSSProperties = {
    textTransform: 'uppercase',
    fontWeight: '700',
    fontFamily: "'Saira Extra Condensed', sans-serif",
    fontSize: '1.5rem',
  };

  return (
    <div className="container-fluid p-0">
      <section className="p-4 p-lg-5" id="terms-of-service">
        <div className="container" style={{ maxWidth: '900px' }}>
          
          <h1 className="mb-5 display-3 fw-bold text-primary">Terms of Service</h1>
          <p className="mb-5 lead"><strong>Last updated: {lastUpdated}</strong></p>

          {/* 1. Acceptance of Terms */}
          <div className="mb-5">
            <h2 className="mb-3" style={subheadingStyle}>1. Acceptance of Terms</h2>
            <p>
              By accessing or using {websiteName} (the &quot;Service&quot;), you agree to be bound by these Terms of Service (&quot;Terms&quot;). 
              If you do not agree with any part of these Terms, you may not use the Service.
            </p>
          </div>

          {/* 2. Description of Service */}
          <div className="mb-5">
            <h2 className="mb-3" style={subheadingStyle}>2. Description of Service</h2>
            <p>
              {websiteName} provides a personal Bible study planning service. 
              Users can connect their Google Calendar to allow the Service to create a dedicated calendar for Bible study events. 
              The Service may also read your other calendar events to avoid scheduling conflicts. 
              The Service uses AI (OpenAI) to generate a personalized study schedule based on user-provided preferences and progress.
            </p>
          </div>

          {/* 3. Eligibility */}
          <div className="mb-5">
            <h2 className="mb-3" style={subheadingStyle}>3. Eligibility</h2>
            <p>
              You must be at least 13 years old to use the Service. By using {websiteName}, you represent and warrant that you meet this age requirement.
            </p>
          </div>

          {/* 4. User Accounts */}
          <div className="mb-5">
            <h2 className="mb-3" style={subheadingStyle}>4. User Accounts</h2>
            <p>
              In order to use the Service, you may need to create an account and connect your Google Calendar. 
              You are responsible for maintaining the confidentiality of your account credentials. 
              You agree to notify us immediately of any unauthorized use of your account.
            </p>
          </div>

          {/* 5. Use of the Service */}
          <div className="mb-5">
            <h2 className="mb-3" style={subheadingStyle}>5. Use of the Service</h2>
            <ul>
              <li>You may use the Service only for lawful purposes and in accordance with these Terms.</li>
              <li>You agree not to interfere with or disrupt the Service or servers.</li>
              <li>All data generated by the AI is provided for personal, non-commercial use.</li>
              <li>You are responsible for reviewing the study schedule before adding events to your calendar.</li>
            </ul>
          </div>

          {/* 6. Calendar and AI Data */}
          <div className="mb-5">
            <h2 className="mb-3" style={subheadingStyle}>6. Calendar and AI Data</h2>
            <p>
              By connecting your Google Calendar, you authorize {websiteName} to create a dedicated calendar and read your other calendars for scheduling purposes. 
              The AI uses your calendar data only to generate conflict-free study plans. 
              We do not access, modify, or store your existing events outside of the AI processing needed to generate the plan.
            </p>
            <p>
              The AI is provided by OpenAI. Data sent to OpenAI is limited to the scheduling input described above and is not stored beyond the session. 
              No sensitive personal information is shared with OpenAI beyond what is necessary for generating your Bible study schedule.
            </p>
          </div>

          {/* 7. Third-Party Services */}
          <div className="mb-5">
            <h2 className="mb-3" style={subheadingStyle}>7. Third-Party Services</h2>
            <p>
              We may integrate third-party services such as OpenAI for AI generation and Stripe for payments. 
              Your use of these third-party services is subject to their own terms and privacy policies.
            </p>
          </div>

          {/* 8. Payments */}
          <div className="mb-5">
            <h2 className="mb-3" style={subheadingStyle}>8. Payments</h2>
            <p>
              Any payments made through {websiteName} are processed by Stripe. We do not store your full payment information. 
              You agree to Stripe’s Terms of Service and Privacy Policy when making a payment.
            </p>
          </div>

          {/* 9. Termination */}
          <div className="mb-5">
            <h2 className="mb-3" style={subheadingStyle}>9. Termination</h2>
            <p>
              We may suspend or terminate your access to the Service at any time, without notice, for violation of these Terms or for any other reason.
            </p>
          </div>

          {/* 10. Disclaimers */}
          <div className="mb-5">
            <h2 className="mb-3" style={subheadingStyle}>10. Disclaimers</h2>
            <p>
              The Service is provided &quot;as is&quot; without warranties of any kind. We do not guarantee the accuracy, reliability, or completeness of the AI-generated study plans. 
              You are responsible for verifying the schedule and ensuring it meets your personal needs.
            </p>
          </div>

          {/* 11. Limitation of Liability */}
          <div className="mb-5">
            <h2 className="mb-3" style={subheadingStyle}>11. Limitation of Liability</h2>
            <p>
              {companyName} shall not be liable for any indirect, incidental, special, or consequential damages arising from your use of the Service, including any errors or omissions in AI-generated plans.
            </p>
          </div>

          {/* 12. Changes to Terms */}
          <div className="mb-5">
            <h2 className="mb-3" style={subheadingStyle}>12. Changes to Terms</h2>
            <p>
              We may update these Terms from time to time. Any changes will be posted on this page with an updated &quot;Last Updated&quot; date. 
              Your continued use of the Service constitutes acceptance of the new Terms.
            </p>
          </div>

          {/* 13. Contact Us */}
          <div className="mb-5">
            <h2 className="mb-3" style={subheadingStyle}>13. Contact Us</h2>
            <p>
              If you have questions about these Terms, please contact us:
            </p>
            <ul>
              <li>Email: <a href={`mailto:${contactEmail}`}>{contactEmail}</a></li>
              <li>Contact page: <a href={contactPageUrl}>{contactPageUrl}</a></li>
            </ul>
          </div>

        </div>
      </section>
    </div>
  );
};

export default function TermsPage() {
  return <TermsOfService {...defaultTermsProps} />;
}
